/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as IndexRouteImport } from './routes/index'

const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grocery': typeof GroceryRoute
  '/insights': typeof InsightsRoute
  '/library': typeof LibraryRoute
  '/plan': typeof PlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grocery' | '/insights' | '/library' | '/plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grocery' | '/insights' | '/library' | '/plan'
  id: '__root__' | '/' | '/grocery' | '/insights' | '/library' | '/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroceryRoute: typeof GroceryRoute
  InsightsRoute: typeof InsightsRoute
  LibraryRoute: typeof LibraryRoute
  PlanRoute: typeof PlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroceryRoute: GroceryRoute,
  InsightsRoute: InsightsRoute,
  LibraryRoute: LibraryRoute,
  PlanRoute: PlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
